version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=iam,lambda,apigateway,secretsmanager,rds,cloudformation,s3,ecr
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=dev
      - AWS_SECRET_ACCESS_KEY=dev
      - EDGE_PORT=4566
      - DEBUG=1
      - LC_LOG=debug
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
    ports:
      - '4566-4597:4566-4597'
      - '6645:6645'
